### ISSUE TITLE
Please upgrade to svelte-apollo 0.4.0 (requires setClient to be called)

### ISSUE THREAD

**Issue by davidpodhola** [CorfitzMe/sapper-w-svelte-apollo#6]
Thanks a lot for this great sample. It works great for svelte-apollo 0.3.0 as it can be easily enhanced to work with a `mutation` too.

The problems start when `svelte-apollo` is upgraded to 0.4.0. It requires calling `setClient`, but as you already mentioned in your code, doing so will break the `sapper` app with `Function called outside component initialization`. Any ideas on how to fix this? Thanks!

**Comment by CorfitzMe** [comment]
Hi @davidpodhola 

I happened to have some time today, and I have given the repo a complete update to latest version of `sapper-start`, latest `svelte apollo` and more... It is however initialised with typescript.

One thing I struggled with was the rollup config, and it seems to me to be solved as I moved the resolve method to be first in the plugins array.

Have a look, and let me know how it goes.. I believe you can simply rename client and server etc. to `.js` files, remove `lang="ts"` from script tags and remove the typescript dependencies for a TS free dev experience. 

Cheers

**Comment by davidpodhola** [comment]
Hi @CorfitzMe ,

thank you very much. It is really great to have such a working sample of apollo client working inside sapper! No worries about TS, I am myself TS-positive as well :-)

It seems to me you removed the GraphQL call that was done before during the SSR to get the ToDo list, is it no longer possible to do it during the hydration phase or do I get it wrong?

Also, I tried to add a `mutation` and unfortunately, it seems to me it is not working. I "fixed" it by passing the `client` argument to the `mutation` function (not using the `getClient` inside `svelte-apollo.es.js`. It works then but does not feel right. Please have a look at the failing mutation here https://github.com/davidpodhola/sapper-w-svelte-apollo/commit/0ab6e7bc1d92a1c4edaa946f1244784cb19e2124.

Thanks again and all the best.

**Comment by CorfitzMe** [comment]
Firstly - thanks man. Glad to hear it is helpful! :D 

In regards to your gist.
A couple of things needs to be changed in this.. Firstly your mutation has to be wrapped in a mutation action. Otherwise it will be assumed to be a `query` by the GraphQL API. 

```js
const ADD = gql`
    mutation {
      createTodo(input: { title: "test 123", completed: false }) {
        id
      }
    }
  `;
```

Next up - your problem is related to the mutation method having to be instantiated in the "root" of your script, and then referenced in an async `add` function.

```js
const addTodo = mutation(ADD);

  async function add() {
    try {
      await addTodo({});
    } catch (error) {
      // TODO
      console.log(error);
    }
  }
```

I will update the repo with this example as well..

**Comment by CorfitzMe** [comment]
Let me have a second look to add the ssr as well ;)

**Comment by davidpodhola** [comment]
Thanks a ton. After moving the mutation method to the "root" of the script, the mutation started to work in my real app (I had the `mutation` action there), which is simply great 💯

**Comment by CorfitzMe** [comment]
Cheers mate.. I have just updated the repo with the ssr example  ;) Best of luck!

**Comment by davidpodhola** [comment]
Works like a charm. You are the best :-)
